services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: guests_api
    restart: unless-stopped
    ports:
      - '3001:3001'
    environment:
      NODE_ENV: production
      PORT: 3001
      MONGO_URI: ${MONGO_URI}
      API_VERSION: v1
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX: 100
    networks:
      - guests_network

networks:
  guests_network:
    name: guests_network
    driver: bridge
