import { Router } from 'express';
import { guestController } from '../controllers/guest.controller';
import { validate } from '../middlewares/validate.middleware';
import { createGuestSchema, updateGuestSchema, guestQuerySchema } from '../utils/validation';

const router = Router();

/**
 * @openapi
 * /guests:
 *   get:
 *     tags: [Guests]
 *     summary: Get all guests
 *     description: >
 *       Returns a paginated list of all guests (solo and couples).
 *       Supports filtering by country, continent, and visited date range.
 *     parameters:
 *       - in: query
 *         name: page
 *         schema: { type: integer, default: 1, minimum: 1 }
 *         description: Page number
 *       - in: query
 *         name: limit
 *         schema: { type: integer, default: 10, minimum: 1, maximum: 100 }
 *         description: Items per page
 *       - in: query
 *         name: country
 *         schema: { type: string }
 *         description: Filter by country name (case-insensitive, partial match)
 *         example: Morocco
 *       - in: query
 *         name: continent
 *         schema:
 *           type: string
 *           enum: [Africa, South America, North America, Central America, Europe, Asia, Oceania]
 *         description: Filter by continent
 *       - in: query
 *         name: from
 *         schema: { type: string }
 *         description: "Start of visited date range. Format: month-year (e.g. november-2022)"
 *         example: november-2022
 *       - in: query
 *         name: to
 *         schema: { type: string }
 *         description: "End of visited date range. Format: month-year (e.g. august-2025)"
 *         example: august-2025
 *     responses:
 *       200:
 *         description: Guests retrieved successfully
 *         content:
 *           application/json:
 *             schema:
 *               allOf:
 *                 - $ref: '#/components/schemas/ApiSuccess'
 *                 - type: object
 *                   properties:
 *                     data:
 *                       $ref: '#/components/schemas/PaginatedGuests'
 *       400:
 *         description: Invalid query parameters
 *         content:
 *           application/json:
 *             schema: { $ref: '#/components/schemas/ApiError' }
 *       500:
 *         description: Internal server error
 *         content:
 *           application/json:
 *             schema: { $ref: '#/components/schemas/ApiError' }
 */
router.get('/', validate(guestQuerySchema, 'query'), guestController.getAll.bind(guestController));

/**
 * @openapi
 * /guests/{id}:
 *   get:
 *     tags: [Guests]
 *     summary: Get a guest by ID
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema: { type: string }
 *         description: The guest's guestId
 *         example: aT84plm2UiN
 *     responses:
 *       200:
 *         description: Guest retrieved successfully
 *         content:
 *           application/json:
 *             schema:
 *               allOf:
 *                 - $ref: '#/components/schemas/ApiSuccess'
 *                 - type: object
 *                   properties:
 *                     data:
 *                       $ref: '#/components/schemas/Guest'
 *       404:
 *         description: Guest not found
 *         content:
 *           application/json:
 *             schema: { $ref: '#/components/schemas/ApiError' }
 *       500:
 *         description: Internal server error
 *         content:
 *           application/json:
 *             schema: { $ref: '#/components/schemas/ApiError' }
 */
router.get('/:id', guestController.getById.bind(guestController));

/**
 * @openapi
 * /guests:
 *   post:
 *     tags: [Guests]
 *     summary: Create a new guest
 *     description: >
 *       Creates a solo guest or a couple. Set `wasACouple: true` and provide
 *       a `coupleInfo` array with exactly 2 members for couples.
 *       `guestId` and `coupleId` are auto-generated by the server.
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             oneOf:
 *               - $ref: '#/components/schemas/CreateSoloGuestDto'
 *               - $ref: '#/components/schemas/CreateCoupleGuestDto'
 *           examples:
 *             solo:
 *               summary: Solo guest example
 *               value:
 *                 nights: 2
 *                 stayed: true
 *                 rating: 4
 *                 countryCode: mar
 *                 prefixCode: "+212"
 *                 country: Morocco
 *                 flag: "🇲🇦"
 *                 continent: Africa
 *                 fullName: Simo Amri
 *                 birthplace: "Casablanca"
 *                 livingIn: "Essaouira"
 *                 birthyear: 1991
 *                 occupation: ["GIS specialist"]
 *                 gender: male
 *                 didWeHangOut: true
 *                 visitedMonth: November
 *                 visitedYear: 2025
 *                 urlProfileCs: "simo-amri"
 *                 wasACouple: false
 *             couple:
 *               summary: Couple guest example
 *               value:
 *                 nights: 3
 *                 stayed: true
 *                 didWeHangOut: true
 *                 visitedMonth: June
 *                 visitedYear: 2025
 *                 wasACouple: true
 *                 gift: ["handmade card"]
 *                 coupleInfo:
 *                   - rating: 4
 *                     countryCode: arg
 *                     prefixCode: "+54"
 *                     country: Argentina
 *                     flag: "🇦🇷"
 *                     continent: South America
 *                     fullName: Aylen Rivarola
 *                     gender: female
 *                     occupation: ["head chef"]
 *                     urlProfileCs: "aylen-rivarola"
 *                   - rating: 4
 *                     countryCode: arg
 *                     prefixCode: "+54"
 *                     country: Argentina
 *                     flag: "🇦🇷"
 *                     continent: South America
 *                     fullName: Manu Sabanés
 *                     gender: male
 *                     occupation: ["head chef"]
 *                     urlProfileCs: null
 *     responses:
 *       201:
 *         description: Guest created successfully
 *         content:
 *           application/json:
 *             schema:
 *               allOf:
 *                 - $ref: '#/components/schemas/ApiSuccess'
 *                 - type: object
 *                   properties:
 *                     data:
 *                       $ref: '#/components/schemas/Guest'
 *       400:
 *         description: Validation error
 *         content:
 *           application/json:
 *             schema: { $ref: '#/components/schemas/ApiError' }
 *       500:
 *         description: Internal server error
 *         content:
 *           application/json:
 *             schema: { $ref: '#/components/schemas/ApiError' }
 */
router.post('/', validate(createGuestSchema), guestController.create.bind(guestController));

/**
 * @openapi
 * /guests/{id}:
 *   put:
 *     tags: [Guests]
 *     summary: Update a guest
 *     description: >
 *       Partially updates a guest. Only the fields provided in the body
 *       will be updated. `wasACouple` type cannot be changed after creation.
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema: { type: string }
 *         description: The guest's guestId
 *         example: aT84plm2UiN
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             oneOf:
 *               - $ref: '#/components/schemas/CreateSoloGuestDto'
 *               - $ref: '#/components/schemas/CreateCoupleGuestDto'
 *     responses:
 *       200:
 *         description: Guest updated successfully
 *         content:
 *           application/json:
 *             schema:
 *               allOf:
 *                 - $ref: '#/components/schemas/ApiSuccess'
 *                 - type: object
 *                   properties:
 *                     data:
 *                       $ref: '#/components/schemas/Guest'
 *       400:
 *         description: Validation error or invalid operation
 *         content:
 *           application/json:
 *             schema: { $ref: '#/components/schemas/ApiError' }
 *       404:
 *         description: Guest not found
 *         content:
 *           application/json:
 *             schema: { $ref: '#/components/schemas/ApiError' }
 *       500:
 *         description: Internal server error
 *         content:
 *           application/json:
 *             schema: { $ref: '#/components/schemas/ApiError' }
 */
router.put('/:id', validate(updateGuestSchema), guestController.update.bind(guestController));

/**
 * @openapi
 * /guests/{id}:
 *   delete:
 *     tags: [Guests]
 *     summary: Delete a guest
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema: { type: string }
 *         description: The guest's guestId
 *         example: aT84plm2UiN
 *     responses:
 *       200:
 *         description: Guest deleted successfully
 *         content:
 *           application/json:
 *             schema:
 *               allOf:
 *                 - $ref: '#/components/schemas/ApiSuccess'
 *                 - type: object
 *                   properties:
 *                     data:
 *                       nullable: true
 *                       example: null
 *       404:
 *         description: Guest not found
 *         content:
 *           application/json:
 *             schema: { $ref: '#/components/schemas/ApiError' }
 *       500:
 *         description: Internal server error
 *         content:
 *           application/json:
 *             schema: { $ref: '#/components/schemas/ApiError' }
 */
router.delete('/:id', guestController.delete.bind(guestController));

export default router;
