import swaggerJsdoc from 'swagger-jsdoc';
import { env } from './env';

const CONTINENTS = ['Africa', 'America', 'Europe', 'Asia', 'Oceania'];
const REGIONS = [
  'North America',
  'Central America',
  'South America',
  'Caribbean',
  'Middle East Asia',
  'Southeast Asia',
  'Eastern Asia',
  'South Asia',
  'Central Asia',
  'West Europe',
  'Scandinavia',
  'Southern Europe',
  'Northern Europe',
  'Eastern Europe',
  'Oceania',
  'Africa',
];
const GENDERS = ['male', 'female', 'trans'];

const options: swaggerJsdoc.Options = {
  definition: {
    openapi: '3.0.3',
    info: { title: 'Guests API', version: '1.0.0', description: 'REST API for couchsurfing guests.' },
    servers: [{ url: `http://localhost:${env.PORT}/api/${env.API_VERSION}`, description: 'Local dev' }],
    tags: [{ name: 'Guests', description: 'Guest management endpoints' }],
    components: {
      schemas: {
        IndividualInfo: {
          type: 'object',
          required: ['hometownCode', 'continent', 'region', 'fullName', 'gender'],
          properties: {
            rating: { type: 'number', nullable: true, minimum: 1, maximum: 5 },
            hometownCode: { type: 'string', example: 'CHN', description: 'ISO code of hometown country' },
            livingInCode: {
              type: 'string',
              nullable: true,
              example: 'DEU',
              description: 'ISO code of current country of residence (optional)',
            },
            prefixCode: { type: 'string', nullable: true, example: '+86' },
            continent: { type: 'string', enum: CONTINENTS },
            region: { type: 'string', enum: REGIONS },
            fullName: { type: 'string', example: '苠全 Randy' },
            hometown: { type: 'string', nullable: true, example: 'Zhangjiajie, Hunan' },
            livingIn: { type: 'string', nullable: true, example: 'Berlin' },
            birthDate: {
              type: 'string',
              nullable: true,
              example: '2000',
              description: '"YYYY", "Month YYYY" or "DD Month YYYY"',
            },
            occupation: { type: 'array', items: { type: 'string' } },
            urlProfileCs: { nullable: true },
            gender: { type: 'string', enum: GENDERS },
            whatsapp: { type: 'string', nullable: true },
            instagram: { type: 'string', nullable: true },
          },
        },
        GuestBase: {
          type: 'object',
          properties: {
            guestId: { type: 'string', example: 'aT84plm2UiN' },
            nights: { type: 'number', example: 2 },
            stayed: { type: 'boolean' },
            hangOut: { type: 'boolean' },
            visitedDate: { type: 'string', example: 'January 2026', description: '"Month Year" or "DD Month Year"' },
            isFirstTime: { type: 'boolean', default: false },
            gift: { type: 'array', items: { type: 'string' }, nullable: true },
            comments: { type: 'string', nullable: true },
            wasACouple: { type: 'boolean' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        SoloGuest: {
          allOf: [
            { $ref: '#/components/schemas/GuestBase' },
            { $ref: '#/components/schemas/IndividualInfo' },
            {
              type: 'object',
              properties: {
                wasACouple: { type: 'boolean', enum: [false] },
                coupleId: { nullable: true },
              },
            },
          ],
        },
        CoupleGuest: {
          allOf: [
            { $ref: '#/components/schemas/GuestBase' },
            {
              type: 'object',
              properties: {
                wasACouple: { type: 'boolean', enum: [true] },
                coupleId: { type: 'string' },
                coupleInfo: {
                  type: 'array',
                  minItems: 2,
                  maxItems: 2,
                  items: { $ref: '#/components/schemas/IndividualInfo' },
                },
              },
            },
          ],
        },
        Guest: {
          oneOf: [{ $ref: '#/components/schemas/SoloGuest' }, { $ref: '#/components/schemas/CoupleGuest' }],
          discriminator: { propertyName: 'wasACouple' },
        },
        GuestListItem: {
          type: 'object',
          description: 'Projected guest for list view.',
          properties: {
            guestId: { type: 'string' },
            wasACouple: { type: 'boolean' },
            isFirstTime: { type: 'boolean' },
            nights: { type: 'number' },
            stayed: { type: 'boolean' },
            visitedDate: { type: 'string', example: 'January 2026' },
            hangOut: { type: 'boolean' },
            fullName: { type: 'string', nullable: true },
            hometownCode: { type: 'string', nullable: true },
            livingInCode: { type: 'string', nullable: true },
            prefixCode: { type: 'string', nullable: true },
            continent: { type: 'string', enum: CONTINENTS, nullable: true },
            region: { type: 'string', enum: REGIONS, nullable: true },
            age: { type: 'number', nullable: true },
            occupation: { type: 'array', items: { type: 'string' }, nullable: true },
            livingIn: { type: 'string', nullable: true },
            hometown: { type: 'string', nullable: true },
            rating: { type: 'number', nullable: true },
            gender: { type: 'string', enum: GENDERS, nullable: true },
            whatsapp: { type: 'string', nullable: true },
            coupleInfo: {
              type: 'array',
              nullable: true,
              minItems: 2,
              maxItems: 2,
              items: {
                type: 'object',
                properties: {
                  fullName: { type: 'string' },
                  hometownCode: { type: 'string' },
                  livingInCode: { type: 'string', nullable: true },
                  prefixCode: { type: 'string', nullable: true },
                  continent: { type: 'string', enum: CONTINENTS },
                  region: { type: 'string', enum: REGIONS },
                  age: { type: 'number', nullable: true },
                  occupation: { type: 'array', items: { type: 'string' } },
                  livingIn: { type: 'string', nullable: true },
                  hometown: { type: 'string', nullable: true },
                  rating: { type: 'number', nullable: true },
                  gender: { type: 'string', enum: GENDERS },
                  whatsapp: { type: 'string', nullable: true },
                },
              },
            },
          },
        },
        CreateSoloGuestDto: {
          type: 'object',
          required: [
            'nights',
            'stayed',
            'hometownCode',
            'continent',
            'region',
            'fullName',
            'gender',
            'hangOut',
            'visitedDate',
          ],
          properties: {
            nights: { type: 'number', minimum: 1 },
            stayed: { type: 'boolean' },
            rating: { type: 'number', nullable: true, minimum: 1, maximum: 5 },
            hometownCode: { type: 'string', example: 'CHN' },
            livingInCode: { type: 'string', nullable: true, example: 'DEU' },
            prefixCode: { type: 'string', nullable: true },
            continent: { type: 'string', enum: CONTINENTS },
            region: { type: 'string', enum: REGIONS },
            fullName: { type: 'string' },
            hometown: { type: 'string', nullable: true },
            livingIn: { type: 'string', nullable: true },
            birthDate: { type: 'string', nullable: true, description: '"YYYY", "Month YYYY" or "DD Month YYYY"' },
            occupation: { type: 'array', items: { type: 'string' } },
            urlProfileCs: { nullable: true },
            gender: { type: 'string', enum: GENDERS },
            whatsapp: { type: 'string', nullable: true },
            instagram: { type: 'string', nullable: true },
            gift: { type: 'array', items: { type: 'string' }, nullable: true },
            comments: { type: 'string', nullable: true },
            hangOut: { type: 'boolean' },
            visitedDate: { type: 'string', example: 'January 2026', description: '"Month Year" or "DD Month Year"' },
            isFirstTime: { type: 'boolean', default: false },
            wasACouple: { type: 'boolean', enum: [false] },
          },
        },
        CreateCoupleGuestDto: {
          type: 'object',
          required: ['nights', 'stayed', 'hangOut', 'visitedDate', 'wasACouple', 'coupleInfo'],
          properties: {
            nights: { type: 'number', minimum: 1 },
            stayed: { type: 'boolean' },
            hangOut: { type: 'boolean' },
            visitedDate: { type: 'string', example: 'June 2025' },
            isFirstTime: { type: 'boolean', default: false },
            wasACouple: { type: 'boolean', enum: [true] },
            gift: { type: 'array', items: { type: 'string' }, nullable: true },
            comments: { type: 'string', nullable: true },
            coupleInfo: { type: 'array', minItems: 2, maxItems: 2, items: { $ref: '#/components/schemas/IndividualInfo' } },
          },
        },
        PaginatedGuests: {
          type: 'object',
          properties: {
            success: { type: 'boolean', example: true },
            message: { type: 'string' },
            data: { type: 'array', items: { $ref: '#/components/schemas/GuestListItem' } },
            total: { type: 'number', example: 120 },
            page: { type: 'number', example: 1 },
            limit: { type: 'number', example: 10 },
            totalPages: { type: 'number', example: 12 },
            hasNextPage: { type: 'boolean' },
            hasPrevPage: { type: 'boolean' },
          },
        },
        ApiSuccess: {
          type: 'object',
          properties: { success: { type: 'boolean', example: true }, message: { type: 'string' }, data: {} },
        },
        ApiError: {
          type: 'object',
          properties: {
            success: { type: 'boolean', example: false },
            message: { type: 'string' },
            errors: { type: 'array', items: { type: 'object' } },
          },
        },
      },
    },
  },
  apis: ['./src/routes/*.ts'],
};

export const swaggerSpec = swaggerJsdoc(options);
